#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Patches an app/build.gradle.kts generated by `flutter create` (Kotlin DSL). Called by tools/bootstrap.ps1.

.DESCRIPTION
    Every edit is written to be idempotent on its own:
      - simple value changes (minSdk, compileSdk, targetSdk) replace the *original* Flutter-template text
        (e.g. "minSdk = flutter.minSdkVersion"), which is gone after the first run, so a second run's search
        matches nothing and the line is left as we set it.
      - inserted blocks (signing config loader, flavors) are guarded by an explicit marker comment
        ("// HOMESCHOOLING:") checked before inserting.
      - the buildTypes { release { ... } } block is matched against the exact text the template ships today
        and replaced wholesale; if that text is not found (because Flutter changed the template, or this
        script already patched it) the *other* branch of the check confirms our own marker is present, and
        only fails if neither is true.
      - line endings: the file `flutter create` writes on Windows uses CRLF, but this script's literal
        expected-text blocks are LF (authored on Linux). Multi-line exact-text matches (step 5) would
        silently fail on CRLF input, so content is normalized to LF on read and restored to CRLF on write.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$Path
)

$ErrorActionPreference = 'Stop'

function Fail([string]$Message) {
    Write-Host "ERROR: $Message" -ForegroundColor Red
    throw $Message
}

$rawContent = Get-Content -Raw -Path $Path
$hadCrLf = $rawContent -match "`r`n"
$content = $rawContent -replace "`r`n", "`n"
$original = $content

# --- 1. SDK versions -------------------------------------------------------
$content = $content -replace 'minSdk\s*=\s*flutter\.minSdkVersion', 'minSdk = 26'
$content = $content -replace 'compileSdk\s*=\s*flutter\.compileSdkVersion', 'compileSdk = 36'
$content = $content -replace 'targetSdk\s*=\s*flutter\.targetSdkVersion', 'targetSdk = 36'

if ($content -notmatch 'minSdk\s*=\s*26') {
    Fail "Could not find or set minSdk = 26 in $Path (expected 'minSdk = flutter.minSdkVersion' or 'minSdk = 26' already)."
}

# --- 2. key.properties loader (top of file, before the android {} block) --
$signingLoaderMarker = '// HOMESCHOOLING: release signing'
if ($content -notmatch [regex]::Escape($signingLoaderMarker)) {
    $anchor = 'plugins {'
    if ($content -notmatch [regex]::Escape($anchor)) {
        Fail "Could not find the 'plugins {' anchor at the top of $Path to insert the signing config loader before it."
    }
    $loader = @"
import java.util.Properties

$signingLoaderMarker (reads android/key.properties, which is gitignored — see README.md)
val keystorePropertiesFile = rootProject.file("key.properties")
val keystoreProperties = Properties()
if (keystorePropertiesFile.exists()) {
    keystorePropertiesFile.inputStream().use { keystoreProperties.load(it) }
}

"@
    $content = $content.Replace($anchor, $loader + $anchor)
}

# --- 3. signingConfigs { create("release") { ... } } -----------------------
$signingConfigsMarker = 'signingConfigs {'
if ($content -notmatch [regex]::Escape($signingConfigsMarker)) {
    $anchor = 'ndkVersion = flutter.ndkVersion'
    if ($content -notmatch [regex]::Escape($anchor)) {
        Fail "Could not find 'ndkVersion = flutter.ndkVersion' in $Path to anchor the signingConfigs insertion."
    }
    $block = @'
ndkVersion = flutter.ndkVersion

    // resValue() in productFlavors below requires this to be explicitly enabled (off by default in modern AGP).
    buildFeatures {
        resValues = true
    }

    signingConfigs {
        create("release") {
            if (keystorePropertiesFile.exists()) {
                keyAlias = keystoreProperties["keyAlias"] as String?
                keyPassword = keystoreProperties["keyPassword"] as String?
                storeFile = (keystoreProperties["storeFile"] as String?)?.let { file(it) }
                storePassword = keystoreProperties["storePassword"] as String?
            }
        }
    }
'@
    $content = $content.Replace($anchor, $block)
}

# --- 4. flavorDimensions + productFlavors (dev/nonprod/prod) --------------
$flavorMarker = '// HOMESCHOOLING: flavors'
if ($content -notmatch [regex]::Escape($flavorMarker)) {
    $anchor = 'versionName = flutter.versionName'
    if ($content -notmatch [regex]::Escape($anchor)) {
        Fail "Could not find 'versionName = flutter.versionName' in $Path to anchor the productFlavors insertion after defaultConfig."
    }
    # Insert right after the defaultConfig block's closing brace, which is the first "    }" following the
    # versionName line.
    $idx = $content.IndexOf($anchor)
    if ($idx -lt 0) { Fail "Anchor '$anchor' disappeared unexpectedly while patching $Path." }
    $closeIdx = $content.IndexOf('    }', $idx)
    if ($closeIdx -lt 0) { Fail "Could not find defaultConfig's closing brace after '$anchor' in $Path." }
    $insertAt = $closeIdx + 5 # length of "    }"
    $flavorsBlock = @"


    $flavorMarker
    flavorDimensions += "env"
    productFlavors {
        create("dev") {
            dimension = "env"
            applicationIdSuffix = ".dev"
            resValue(type = "string", name = "app_name", value = "HomeSchooling Dev")
        }
        create("nonprod") {
            dimension = "env"
            applicationIdSuffix = ".nonprod"
            resValue(type = "string", name = "app_name", value = "HomeSchooling Staging")
        }
        create("prod") {
            dimension = "env"
            resValue(type = "string", name = "app_name", value = "HomeSchooling")
        }
    }
"@
    $content = $content.Insert($insertAt, $flavorsBlock)
}

# --- 5. buildTypes { release { ... } }: real signing + minify -------------
$releaseMarker = '// HOMESCHOOLING: release build type'
if ($content -notmatch [regex]::Escape($releaseMarker)) {
    $originalReleaseBlock = @'
    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig = signingConfigs.getByName("debug")
        }
    }
'@
    $patchedReleaseBlock = @"
    buildTypes {
        release {
            $releaseMarker
            signingConfig = if (keystorePropertiesFile.exists()) signingConfigs.getByName("release") else signingConfigs.getByName("debug")
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }
"@
    if ($content.Contains($originalReleaseBlock)) {
        $content = $content.Replace($originalReleaseBlock, $patchedReleaseBlock)
    } else {
        Fail "Could not find the expected buildTypes { release { ... } } block in $Path to patch it for release signing/minification. The Flutter app template may have changed — update tools/lib/patch-build-gradle-kts.ps1's `$originalReleaseBlock to match, then re-run."
    }
}

if ($content -ne $original) {
    if ($hadCrLf) {
        $content = $content -replace "`n", "`r`n"
    }
    Set-Content -Path $Path -Value $content -NoNewline
    Write-Host "  Patched."
} else {
    Write-Host "  Already patched (no changes)."
}
