#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Patches an app/build.gradle generated by `flutter create` (Groovy DSL). Called by tools/bootstrap.ps1.

.DESCRIPTION
    Kotlin DSL (build.gradle.kts) is Flutter's default template as of the SDK version this repo targets — see
    tools/lib/patch-build-gradle-kts.ps1, which is exercised by tools/test-bootstrap.ps1 against a template
    fetched from the Flutter repo. This Groovy path exists for a project that was migrated from (or created
    with) the older Groovy template, uses the same anchor-based, idempotent approach, but is less exhaustively
    verified — if `flutter create` ever hands you a build.gradle here and this script's anchors don't match,
    it fails with a clear message rather than mangling the file; patch by hand and note it in a PR.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$Path
)

$ErrorActionPreference = 'Stop'

function Fail([string]$Message) {
    Write-Host "ERROR: $Message" -ForegroundColor Red
    throw $Message
}

$content = Get-Content -Raw -Path $Path
$original = $content

# --- 1. SDK versions -------------------------------------------------------
$content = $content -replace 'minSdkVersion\s+flutter\.minSdkVersion', 'minSdkVersion 26'
$content = $content -replace 'compileSdkVersion\s+flutter\.compileSdkVersion', 'compileSdkVersion 36'
$content = $content -replace 'targetSdkVersion\s+flutter\.targetSdkVersion', 'targetSdkVersion 36'

if ($content -notmatch 'minSdkVersion\s+26') {
    Fail "Could not find or set minSdkVersion 26 in $Path (expected 'minSdkVersion flutter.minSdkVersion' or already 26)."
}

# --- 2. key.properties loader (top of file) --------------------------------
$signingLoaderMarker = '// HOMESCHOOLING: release signing'
if ($content -notmatch [regex]::Escape($signingLoaderMarker)) {
    $anchor = "def flutterVersionCode = localProperties.getProperty('flutter.versionCode')"
    if ($content -notmatch [regex]::Escape($anchor)) {
        Fail "Could not find the flutterVersionCode anchor near the top of $Path to insert the signing config loader before it."
    }
    $loader = @"
def keystorePropertiesFile = rootProject.file('key.properties')
def keystoreProperties = new Properties()
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}
$signingLoaderMarker

"@
    $content = $content.Replace($anchor, $loader + $anchor)
}

# --- 3. signingConfigs { release { ... } } ---------------------------------
if ($content -notmatch [regex]::Escape('signingConfigs {')) {
    $anchor = 'defaultConfig {'
    if ($content -notmatch [regex]::Escape($anchor)) {
        Fail "Could not find 'defaultConfig {' in $Path to anchor the signingConfigs insertion."
    }
    $block = @'
signingConfigs {
        release {
            if (keystorePropertiesFile.exists()) {
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
                storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
                storePassword keystoreProperties['storePassword']
            }
        }
    }

    defaultConfig {
'@
    $content = $content.Replace($anchor, $block)
}

# --- 4. flavors (dev/nonprod/prod) -----------------------------------------
$flavorMarker = '// HOMESCHOOLING: flavors'
if ($content -notmatch [regex]::Escape($flavorMarker)) {
    $anchor = 'buildTypes {'
    if ($content -notmatch [regex]::Escape($anchor)) {
        Fail "Could not find 'buildTypes {' in $Path to anchor the productFlavors insertion before it."
    }
    $flavorsBlock = @"
$flavorMarker
    flavorDimensions "env"
    productFlavors {
        dev {
            dimension "env"
            applicationIdSuffix ".dev"
            resValue "string", "app_name", "HomeSchooling Dev"
        }
        nonprod {
            dimension "env"
            applicationIdSuffix ".nonprod"
            resValue "string", "app_name", "HomeSchooling Staging"
        }
        prod {
            dimension "env"
            resValue "string", "app_name", "HomeSchooling"
        }
    }

    $anchor
"@
    $content = $content.Replace($anchor, $flavorsBlock)
}

# --- 5. buildTypes.release: real signing + minify ---------------------------
$releaseMarker = '// HOMESCHOOLING: release build type'
if ($content -notmatch [regex]::Escape($releaseMarker)) {
    $originalReleaseBlock = @'
        release {
            signingConfig signingConfigs.debug
        }
'@
    $patchedReleaseBlock = @"
        release {
            $releaseMarker
            signingConfig keystorePropertiesFile.exists() ? signingConfigs.release : signingConfigs.debug
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
"@
    if ($content.Contains($originalReleaseBlock)) {
        $content = $content.Replace($originalReleaseBlock, $patchedReleaseBlock)
    } else {
        Fail "Could not find the expected 'release { signingConfig signingConfigs.debug }' block in $Path. Patch it by hand for release signing/minification, or update tools/lib/patch-build-gradle-groovy.ps1 to match this project's template."
    }
}

if ($content -ne $original) {
    Set-Content -Path $Path -Value $content -NoNewline
    Write-Host "  Patched."
} else {
    Write-Host "  Already patched (no changes)."
}
